#remote_theme : jekyllup/jekyll-theme-massively
# Site
title:              JoohoK's Technical Blog
bio:                'Jekyll version of the Massively theme by HTML5UP'
description:        "Jekyll version of the Massively theme by HTML5UP"
locale:             en_US
baseurl: "https://JohnNasse.github.io/whatever" # the subpath of your site, e.g. /blog
#url: "https://JohnNasse.github.io" # the base hostname & protocol for your site


# Other
background_image:   /images/bg.jpg


paginate: 6
paginate_path: "/blog/page:num/"

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
